# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rails"
gem "rspec"
gem "selenium-webdriver"
gem "capybara"
gem "cucumber"
gem "capybara-chrome_response_headers"
gem "report_builder"
gem "caxlsx"
gem "caxlsx_rails"